name: pull_request

on: [pull_request]

jobs:
  assembleDebug:

    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v1

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build
        run: ./gradlew clean assembleDebug

      - name: Lint Check
        run: ./gradlew lintDebug

      - name: Unit Tests
        run: ./gradlew testDebugUnitTest
